### ISSUE TITLE
请求增加 屏蔽投票弹幕的功能

### ISSUE THREAD

**Issue by hhelibeb** [xmcp/pakku.js#178]
rt，投票弹幕遮挡画面且容易导致误触，求屏蔽功能

补充：例子请看这个视频的第3秒，https://www.bilibili.com/video/BV1t54y1L72m

**Comment by xmcp** [comment]
目前投票弹幕是跟播放器配置一起下发，和正常弹幕不在同一个请求里（与 #159 相同）。pakku根本不处理这个请求，所以屏蔽这个不太好实现。

**Comment by xmcp** [comment]
屏蔽投票弹幕的话，感觉直接用css比较好实现？

```css
.bilibili-player-video-popup-item {
    display: none;
}
```
