### ISSUE TITLE
建议增加屏蔽高点赞弹幕的开关

### ISSUE THREAD

**Issue by Jingle-seven** [xmcp/pakku.js#216]
一个屎黄色的点赞真的很影响观感，尤其是很多时候这条弹幕质量还不高
![image](https://user-images.githubusercontent.com/18697377/166406286-87c0658a-658c-4db3-b475-246c1a6fa51d.png)

**Comment by xmcp** [comment]
如果只是觉得点赞图标影响观看的话，可以使用stylus之类的工具添加如下CSS：

```css
.b-danmaku-high-icon {
    display: none;
}
```
