### ISSUE TITLE
如何自定义 Pakku 的弹幕字体？

### ISSUE THREAD

**Issue by sherlcok314159** [xmcp/pakku.js#293]
### 功能内容

我想要增加弹幕字体的设置，比如像 Stylus 那样通过 CSS 来控制字体，但是我没有找到跟弹幕字体相关的类，想来应该是在 Pakku 这里进行设置，如果可以，麻烦新增一个 CSS 选项来让用户定义字体，比如：

```css
@font-face {
  font-family: LXGW WenKai Screen;
  src: url("https://cdn.jsdelivr.net/npm/lxgw-wenkai-subset@1.235.2/woff2/lxgwwenkaiscreen.subset.v1.235.standard.woff2");
}

danmaku-font{
  font-family: LXGW WenKai Screen;
}
```

最后，对作者所做的贡献表示感谢~
