### ISSUE TITLE
[样式建议]那个sql查询的前置文本定位感觉不对

### ISSUE THREAD

**Issue by AnnAngela** [xmcp/pakku.js#54]
然后测了下发现旁边的输入框的高度是20px，而前面的文本高度是14px，有6px的高度差=。=
建议`.pakku-foolbar>.pakku-foolbar-prompt`的样式修改为
```CSS
.pakku-foolbar>.pakku-foolbar-prompt {
    flex: 0 0 250px;
    text-align: right;
    padding-top: 3px;
}
```
就是多一个padding-top来对齐前置文本和输入框内文本（拯救强迫症患者）
